TimeEstim/TimeEstim/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
# from apps.bot.views import ChatterBotAppView, ChatterBotApiView
from apps.bot.views import ChatterBotAppView
from apps.bot.api import ChatterBotView
from apps.core.views import index, plans, profile, signup, templates
from apps.dashbd.api import api_start_timer, api_stop_timer, api_discard_timer, api_get_tasks
from apps.dashbd.views import dashbd
from apps.project.views import project, projects, edit_project, delete_project, task, edit_task, delete_task, edit_step, delete_step, track_step, delete_untracked_step

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', index, name='index'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('plans/', plans, name='plans'),
    path('accounts/profile/', profile, name='profile'),
    path('signup/', signup, name='signup'),
    path('templates/', templates, name='templates'),

    path('api/start_timer/', api_start_timer, name='api_start_timer'),
    path('api/stop_timer/', api_stop_timer, name='api_stop_timer'),
    path('api/discard_timer/', api_discard_timer, name='api_discard_timer'),
    path('api/get_tasks/', api_get_tasks, name='api_get_tasks'),
    path('delete_untracked_step/<int:step_id>/', delete_untracked_step, name='delete_untracked_step'),
    path('<int:project_id>/', project, name='project'),
    path('<int:project_id>/delete/', delete_project, name='delete_project'),
    path('<int:project_id>/<int:task_id>/', task, name='task'),
    path('<int:project_id>/<int:task_id>/edit/', edit_task, name='edit_task'),
    path('<int:project_id>/<int:task_id>/delete/', delete_task, name='delete_task'),
    path('<int:project_id>/<int:task_id>/<int:step_id>/edit/', edit_step, name='edit_step'),
    path('<int:project_id>/<int:task_id>/<int:step_id>/delete/', delete_step, name='delete_step'),
    path('<int:project_id>/edit/', edit_project, name='edit_project'),
    path('track_step/<int:step_id>/', track_step, name='track_step'),
    path('projects/', projects, name='projects'),
    path('dashbd/', dashbd, name='dashbd'),
    url(r'^postbot/', ChatterBotView.as_view(), name='chatterbot'),
    url(r'^bot/', ChatterBotAppView.as_view(), name='bot'),
    # url(r'^admin/', admin.site.urls, name='admin'),
    # url(r'^api/chatterbot/', ChatterBotApiView.as_view(), name='chatterbot'),
]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TimeEstim/apps/project/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.db import models
from .forms import  DateInput
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _
# from bulma_widget import widgets
# Create your models here.

def get_sentinel_user():
    return get_user_model().objects.get_or_create(username='deleted')[0]

class Project(models.Model):
    ONGOING = 'ongoing'
    ARCHIVED = 'archived'
    CHOICES_STATUS = (
        (ONGOING, 'Активный'),
        (ARCHIVED, 'В архиве')
    )
    # PUBLIC = 'public'
    # PRIVATE = 'private'
    # CHOICES_STATUS = (
    #     (PUBLIC, 'Публичный'),
    #     (PRIVATE, 'Закрытый')
    # )
    title = models.CharField(max_length=255)
    creator = models.ForeignKey(User, related_name='projects', on_delete=models.SET(get_sentinel_user))
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=20, choices=CHOICES_STATUS, default=ONGOING)
    importance = models.BooleanField(default=False)
    urgency = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created_at']
        # ordering = ['title']
    # string representation
    def __str__(self):
        return self.title
    
    def registered_time(self):
        return sum(step.minutes for step in self.steps.all())
    
    def num_tasks_todo(self):
        return self.tasks.filter(status=Task.TODO).count()
    
    def num_tasks_ongoing(self):
        return self.tasks.filter(status=Task.ONGOING).count()
    
    def num_tasks_testing(self):
        return self.tasks.filter(status=Task.TESTING).count()

class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ['title', 'status', 'importance', 'urgency']
        labels = {
            'title': _('Название'),
            'status': _('Статус'),
            'importance': _('Важный'),
            'urgency': _('Срочный'),
        }

class Task(models.Model):
    class ScrumPocker(models.IntegerChoices):
        O = 1, _('1')
        T = 2, _('2')
        TH = 3, _('3')
        F = 5, _('5')
        E = 8, _('8')
    TODO = 'todo'
    ONGOING = 'ongoing'
    TESTING = 'testing'
    DONE = 'done'
    ARCHIVED = 'archived'
    CHOICES_STATUS = (
        (TODO, 'Сделать'),
        (ONGOING, 'В процессе'),
        (TESTING, 'Тестируется'),
        (DONE, 'Сделано'),
        (ARCHIVED, 'В архиве')
    )
    project = models.ForeignKey(Project, related_name='tasks', on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    aim = models.CharField(max_length=255, blank = True, null=True, default=None)
    due_date = models.DateField(blank = True, null=True, default=None)
    estimated_length = models.IntegerField(choices=ScrumPocker.choices, default=1)
    responsible_role = models.CharField(max_length=255, blank = True, null=True, default=None)
    resources = models.CharField(max_length=255, blank = True, null=True, default=None)
    creator = models.ForeignKey(User, related_name='tasks', on_delete=models.SET(get_sentinel_user))
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=20, choices=CHOICES_STATUS, default=TODO)
    source = models.CharField(max_length=255, blank = True, null=True, default=None)
    done_date = models.DateField(blank = True, null=True, default=None)

    class Meta:
        ordering = ['-created_at']
    
    def __str__(self):
        return self.title
    
    def registered_time(self):
        return sum(step.minutes for step in self.steps.all())

class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'aim', 'due_date', 'estimated_length', 'responsible_role', 'resources', 'status']
        labels = {
            'title': _('Название'),
            'aim': _('Цель'),
            'due_date': _('Дедлайн'),
            'estimated_length': _('Расчетное время'),
            'responsible_role': _('Отдел / роль'),
            'resources': _('Ресурсы'),
            'status': _('Статус'),
        }
        widgets = {
            'due_date': DateInput(format=('%Y-%m-%d'), attrs={'class':'input', 'placeholder':'гггг-мм-дд', 'type':'date'}),
        }

class Step(models.Model):
    id = models.BigAutoField(primary_key=True)
    project = models.ForeignKey(Project, related_name='steps', on_delete=models.CASCADE, blank=True, null=True)
    task = models.ForeignKey(Task, related_name='steps', on_delete=models.CASCADE, blank=True, null=True)
    minutes = models.IntegerField(default=0)
    is_tracked = models.BooleanField(default=False)
    creator = models.ForeignKey(User, related_name='steps', on_delete=models.CASCADE)
    created_at = models.DateTimeField()

    class Meta:
        ordering = ['-created_at']
    
    def __str__(self):
        if self.task:
            return '%s - %s' % (self.task.title, self.created_at)
        return '%s' % self.created_at

TimeEstim/apps/project/forms.py
from django import forms

class DateInput(forms.DateInput):
    input_type = 'date'
    

TimeEstim/apps/project/views.py
from apps.core.models import User
from datetime import datetime
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from .models import Project, Task, Step, ProjectForm, TaskForm

# Create your views here.

@login_required
def projects(request):
    us = get_object_or_404(User, pk=request.user.pk)
    projects = us.projects.all()
    if request.method == 'POST':
        project = Project.objects.create(creator=request.user)
        form = ProjectForm(request.POST, instance=project)
        form.save()
        messages.info(request, 'Проект добавлен')
        return redirect('projects')
    else:
        form = ProjectForm()
    return render(request, 'project/projects.html', {'form': form, 'projects': projects})

@login_required
def project(request, project_id):
    us = get_object_or_404(User, pk=request.user.pk)
    project = get_object_or_404(Project, creator=us, pk=project_id)
    if request.method == 'POST':
        task = Task.objects.create(project=project, creator=request.user)
        form = TaskForm(request.POST, instance=task)
        form.save()
        messages.info(request, 'Задача добавлена')
        return redirect('project', project_id=project.id)
    else:
        form = TaskForm()
    tasks_todo = project.tasks.filter(status=Task.TODO)
    tasks_ongoing = project.tasks.filter(status=Task.ONGOING)
    tasks_testing = project.tasks.filter(status=Task.TESTING)
    tasks_done = project.tasks.filter(status=Task.DONE)
    tasks_archived = project.tasks.filter(status=Task.ARCHIVED)
    context = {
        'form': form, 
        'project': project, 
        'tasks_todo': tasks_todo, 
        'tasks_ongoing': tasks_ongoing,
        'tasks_testing': tasks_testing,
        'tasks_done': tasks_done,
        'tasks_archived': tasks_archived
    }
    return render(request, 'project/project.html', context)

@login_required
def edit_project(request, project_id):
    us = get_object_or_404(User, pk=request.user.pk)
    project = get_object_or_404(Project, creator=us, pk=project_id)
    if request.method == 'POST':
        title = request.POST.get('title')
        if title:
            status = request.POST.get('status')
            importance = request.POST.get('importance')
            urgency = request.POST.get('urgency')
            project.title = title
            project.status = status
            project.importance = importance
            project.urgency = urgency
            project.save()
            messages.info(request, 'Изменения сохранены')
            return redirect('project', project_id=project.id)
    return render(request, 'project/edit_project.html', {'project': project})

@login_required
def delete_project(request, project_id):
    us = get_object_or_404(User, pk=request.user.pk)
    project = get_object_or_404(Project, creator=us, pk=project_id)
    project.delete()
    messages.info(request, 'Проект удален')
    return redirect('projects')

@login_required
def task(request, project_id, task_id):
    us = get_object_or_404(User, pk=request.user.pk)
    project = get_object_or_404(Project, creator=us, pk=project_id)
    task = get_object_or_404(Task, creator=us, pk=task_id)
    if request.method == 'POST':
        hours = int(request.POST.get('hours', 0))
        minutes = int(request.POST.get('minutes', 0))
        date = '%s %s' % (request.POST.get('date'), datetime.now().time())
        minutes_total = (hours * 60) + minutes
        step = Step.objects.create(project=project, task=task, minutes=minutes_total, creator=request.user, created_at=date, is_tracked=True)
    context = {
        'today': datetime.today(),
        'project': project,
        'task': task,
        'h': [1, 2, 3, 5, 8], 
        'm' : list(range(5,59,5))
    }
    return render(request, 'project/task.html', context)

@login_required
def edit_task(request, project_id, task_id):
    us = get_object_or_404(User, pk=request.user.pk)
    project = get_object_or_404(Project, creator=us, pk=project_id)
    task = get_object_or_404(Task, creator=us, pk=task_id)
    if request.method == 'POST':
        title = request.POST.get('title')
        aim = request.POST.get('aim')
        due_date = request.POST.get('due_date')
        estimated_length = int(request.POST.get('estimated_length'))
        responsible_role = request.POST.get('responsible_role')
        resources = request.POST.get('resources')
        status = request.POST.get('status')
        if title:
            task.title = title
            task.aim = aim
            task.due_date = due_date
            task.estimated_length = estimated_length
            task.responsible_role = responsible_role
            task.resources = resources
            if status == 'done':
                # done_date = datetime.now().time()
                # print(done_date)
                # done_date = datetime.now()
                # print(done_date)
                # done_date = datetime.now().date()
                # print(done_date)
                task.done_date = datetime.now().date()
            else:
                task.done_date = None
                # done_date = None
                # print(done_date)
            # print(status)
            task.status = status
            task.save()
            messages.info(request, 'Изменения сохранены')
            return redirect('task', project_id=project.id, task_id=task.id)
    return render(request, 'project/edit_task.html', {'project': project, 'task': task})

@login_required
def delete_task(request, project_id, task_id):
    us = get_object_or_404(User, pk=request.user.pk)
    project = get_object_or_404(Project, creator=us, pk=project_id)
    task = get_object_or_404(Task, creator=us, pk=task_id)
    task.delete()
    messages.info(request, 'Задача удалена')
    return redirect('project', project_id=project.id)

@login_required
def edit_step(request, project_id, task_id, step_id):
    us = get_object_or_404(User, pk=request.user.pk)
    project = get_object_or_404(Project, creator=us, pk=project_id)
    task = get_object_or_404(Task, creator=us, pk=task_id)
    step = get_object_or_404(Step, creator=us, pk=step_id)
    if request.method == 'POST':
        hours = int(request.POST.get('hours', 0))
        minutes = int(request.POST.get('minutes', 0))
        date = '%s %s' % (request.POST.get('date'), datetime.now().time())
        step.created_at = date
        step.minutes = (hours * 60) + minutes
        step.save()
        messages.info(request, 'Изменения сохранены')
        return redirect('task', project_id=project.id, task_id=task.id)
    hours, minutes = divmod(step.minutes, 60)
    context = {
        'project': project,
        'task': task,
        'step': step,
        'hours': hours,
        'minutes': minutes,
        'h': [1, 2, 3, 5, 8], 'm' : list(range(5,59,5))
    }
    return render(request, 'project/edit_step.html', context)

@login_required
def delete_step(request, project_id, task_id, step_id):
    us = get_object_or_404(User, pk=request.user.pk)
    project = get_object_or_404(Project, creator=us, pk=project_id)
    task = get_object_or_404(Task, creator=us, pk=task_id)
    step = get_object_or_404(Step, creator=us, pk=step_id)
    step.delete()
    messages.info(request, 'Время удалено')
    return redirect('task', project_id=project.id, task_id=task.id)

@login_required
def delete_untracked_step(request, step_id):
    us = get_object_or_404(User, pk=request.user.pk)
    step = get_object_or_404(Step, creator=us, pk=step_id)
    step.delete()
    messages.info(request, 'Время удалено')
    return redirect('dashbd')

@login_required
def track_step(request, step_id):
    us = get_object_or_404(User, pk=request.user.pk)
    step = get_object_or_404(Step, creator=us, pk=step_id)
    projects = us.projects.all()
    if request.method == 'POST':
        # the default is 0
        hours = int(request.POST.get('hours', 0))
        minutes = int(request.POST.get('minutes', 0))
        project = request.POST.get('project')
        task = request.POST.get('task')
        if project and task:
            step.project_id = project
            step.task_id = task
            step.minutes = (hours * 60) + minutes
            step.created_at = '%s %s' % (request.POST.get('date'), step.created_at.time())
            step.is_tracked = True
            step.save()
            messages.info(request, 'Время добавлено')
            return redirect('dashbd')
    hours, minutes = divmod(step.minutes, 60)
    context = {
        'hours': hours,
        'minutes': minutes,
        'projects': projects,
        'step': step,
        'h': list(range(1,23)), 
        'm': list(range(1,59))
    }
    return render(request, 'project/track_step.html', context)

TimeEstim/templates/project/edit_project.html
{% extends 'core/base.html' %}

{% block title %}Редактировать проект {{ project.title }} | {% endblock %}

{% block content %}
    <div id="project-app">
    <br>
        <nav class="breadcrumb" aria-label="breadcrumbs">
            <ul>
                <li><a href="{% url 'projects' %}">Проекты</a></li>
                <li><a href="{% url 'project' project.id %}">{{ project.title }}</a></li>
                <li class="is-active"><a href="{% url 'edit_project' project.id %}" aria-current="page">Редактировать проект</a></li>
            </ul>
        </nav>

        <div class="columns">
            <div class="column">
                <h1 class="title">Редактировать проект</h1>
            </div>
        </div>

        <div class="columns">
            <div class="column is-4">
                <form method="post" action=".">
                    {% csrf_token %}
                    <div class="field">
                        <label>Название</label>
                        <div class="control">
                            <input type="text" name="title" id="id_title" class="input" value="{{ project.title }}">
                        </div>
                    </div>
                    <div class="field">
                        <label>Статус</label>
                        <div class="control">
                            <div class="select">
                                <select name="status" id="id_status">
                                    <option value="ongoing"{% if project.status == 'ongoing' %} selected{% endif %}>Активный</option>
                                    <option value="archived"{% if project.status == 'archived' %} selected{% endif %}>В архиве</option>
                                </select>
                            </div>
                        </div>
                    </div>
                        <div class="field">
                            <label>Важный</label>
                            <div class="control">
                                <div class="select">
                                    <select name="importance" id="id_importance">
                                        <option value="False"{% if project.importance == False %} selected{% endif %}>Нет</option>
                                        <option value="True"{% if project.importance == True %} selected{% endif %}>Да</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="field">
                            <label>Срочный</label>
                            <div class="control">
                                <div class="select">
                                    <select name="urgency" id="id_urgency">
                                        <option value="False"{% if project.urgency == False %} selected{% endif %}>Нет</option>
                                        <option value="True"{% if project.urgency == True %} selected{% endif %}>Да</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    <div class="field">
                        <div class="control">
                            <button class="button is-light">Сохранить изменения</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

TimeEstim/templates/project/edit_step.html
{% extends 'core/base.html' %}

{% block title %}Редактировать запись  {{ project.title }} | {% endblock %}

{% block content %}
    <div id="project-app">
        <nav class="breadcrumb" aria-label="breadcrumbs">
            <ul>
            {# <li><a href="#">Dashboard</a></li>  #}
                <li><a href="{% url 'projects' %}">Проекты</a></li>
                <li><a href="{% url 'project' project.id %}">{{ project.title }}</a></li>
                <li class="is-active"><a href="{% url 'edit_step' project.id task.id step.id %}" aria-current="page">Редактировать запись </a></li>
            </ul>
        </nav>
          
        <div class="columns">
            <div class="column">
                <h1 class="title">Редактировать запись </h1>
            </div>
        </div>

        <div class="columns">
            <div class="column is-4">
                <form method="post" action=".">
                    {% csrf_token %}

                    <div class="field is-grouped">
                        <div class="control">
                            <div class="select">
                                <select name="hours">
                                    <option value="0"{% if hours == 0 %} selected {% endif %}>0ч</option>
                                    {% for i in h %}
                                        <option value="{{ i }}" {% if hours == i %} selected {% endif %}>{{ i }}ч</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>

                        <div class="control">
                            <div class="select">
                                <select name="minutes">
                                    <option value="0"{% if minutes == 0 %} selected {% endif %}>0м</option>
                                    {% for i in m %}
                                        <option value="{{ i }}" {% if minutes == i %} selected {% endif %}>{{ i }}м</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="field">
                        <label>Дата</label>
                        <div class="control">
                            <input type="date" id="id_date" name="date" class="input" value="{{ step.created_at|date:'Y-m-d' }}" placeholder="yyyy-mm-dd">
                        </div>
                    </div>
                      
                    <div class="field">
                        <div class="control">
                            <button class="button is-light">Сохранить изменения</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

TimeEstim/templates/project/edit_task.html
{% extends 'core/base.html' %}

{% block title %}Редактировать задачу {{ project.title }} | {% endblock %}

{% block content %}
    <div id="project-app">
        <nav class="breadcrumb" aria-label="breadcrumbs">
            <ul>
            {# <li><a href="#">Dashboard</a></li>  #}
                <li><a href="{% url 'projects' %}">Проекты</a></li>
                <li><a href="{% url 'project' project.id %}">{{ project.title }}</a></li>
                <li class="is-active"><a href="{% url 'edit_task' project.id task.id %}" aria-current="page">Редактировать задачу</a></li>
            </ul>
        </nav>

        <div class="columns">
            <div class="column">
                <h1 class="title">Редактировать задачу</h1>
            </div>
        </div>

        <div class="columns">
            <div class="column is-4">
                <form method="post" action=".">
                    {% csrf_token %}
                    <div class="field">
                        <label>Название</label>
                        <div class="control">
                            <input type="text" name="title" id="id_title" class="input" value="{{ task.title }}">
                        </div>
                    </div>
                    <div class="field">
                        <label>Цель</label>
                        <div class="control">
                            <input type="text" name="aim" id="id_aim" class="input" value="{{ task.aim|default_if_none:"" }}">
                        </div>
                    </div>
                    <div class="field">
                        <label>Дедлайн</label>
                        <div class="control">
                            <input type="date" id="id_date" name="date" class="input" value="{{ task.due_date|date:'Y-m-d' }}" placeholder="yyyy-mm-dd">
                        </div>
                    </div>
                    <div class="field">
                        <label>Предполагаемая сложность</label>
                        <div class="control">
                            <div class="select">
                                <select name="estimated_length" id="id_estimated_length">
                                    <option value="1"{% if task.estimated_length == 1 %} selected{% endif %}>1</option>
                                    <option value="2"{% if task.estimated_length == 2 %} selected{% endif %}>2</option>
                                    <option value="3"{% if task.estimated_length == 3 %} selected{% endif %}>3</option>
                                    <option value="5"{% if task.estimated_length == 5 %} selected{% endif %}>5</option>
                                    <option value="8"{% if task.estimated_length == 8 %} selected{% endif %}>8</option>
                                </select>                                    
                            </div>
                        </div>
                    </div>
                    <div class="field">
                        <label>Ответственные</label>
                        <div class="control">
                            <input type="text" name="responsible_role" id="id_responsible_role" class="input" value="{{ task.responsible_role|default_if_none:"" }}">
                        </div>
                    </div>
                    <div class="field">
                        <label>Ресурсы</label>
                        <div class="control">
                            <input type="text" name="resources" id="id_resources" class="input" value="{{ task.resources|default_if_none:"" }}">
                        </div>
                    </div>
                    <div class="field">
                        <label>Статус</label>
                        <div class="control">
                            <div class="select">
                                <select name="status" id="id_status">
                                    <option value="todo"{% if task.status == 'todo' %} selected{% endif %}>Сделать</option>
                                    <option value="ongoing"{% if task.status == 'ongoing' %} selected{% endif %}>В процессе</option>
                                    <option value="testing"{% if task.status == 'testing' %} selected{% endif %}>Тестируется</option>
                                    <option value="done"{% if task.status == 'done' %} selected{% endif %}>Выполнено</option>
                                    <option value="archived"{% if task.status == 'archived' %} selected{% endif %}>В архиве</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="field">
                        <div class="control">
                            <button class="button is-light">Сохранить изменения</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}